name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change this to 'master' if your default branch is 'master'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Change this if you're using a different .NET version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build the Project
      run: dotnet build --configuration Release --no-restore

    - name: Publish the Project
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: TrendLeaseApp  # Your Azure App Service name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
